// This file is auto-generated from ServerErrorCode.java
// Do not edit manually - changes will be overwritten
// To regenerate, run: python tools/generator/generate_server_error_enum.py

using System.Collections.Generic;

 public enum ServerErrorCode
{
    SUCCESS = 0,
    HTTP_BAD_REQUEST_400 = 400,
    HTTP_UNAUTHORIZED_401 = 401,
    HTTP_FORBIDDEN_403 = 403,
    HTTP_NOT_FOUND_404 = 404,
    HTTP_SERVER_ERROR_500 = 500,
    ACCOUNT_REGISTER_FAIL_REASON1 = 1001,
    LOGIN_FAIL_REASON1 = 1002,
    ACCOUNT_NOT_FOUND = 1003,
    LOGIN_GOOGLE_FAIL_AUTHENTICATION_TIMEOUT = 1101,
    LOGIN_GOOGLE_FAIL_EXTRACT_AUTHENTICATION = 1102,
    INVALID_TOKEN = 2001,
    CHARACTER_CREATE_FAIL_REASON1 = 3001,
    CHARACTER_NAME_DUPLICATE = 3002,
    CHARACTER_SELECTION_REQUIRED = 3003,
    CHARACTER_NOT_FOUND = 3004,
    FLEET_NOT_FOUND = 4001,
    FLEET_DUPLICATE_NAME = 4002,
    FLEET_ACCESS_DENIED = 4003,
    SHIP_NOT_FOUND = 4004,
    MODULE_NOT_FOUND = 4005,
    MODULE_LEVEL_MISMATCH = 4006,
    MODULE_DATA_NOT_FOUND = 4007,
    INSUFFICIENT_MONEY = 4008,
    INSUFFICIENT_MINERAL = 4009,
    ACTIVE_FLEET_NOT_FOUND = 4010,
    FLEET_MAX_SHIPS_REACHED = 4011,
    INSUFFICIENT_TECH_LEVEL = 4012,
    INSUFFICIENT_MINERAL_RARE = 4013,
    INSUFFICIENT_MINERAL_EXOTIC = 4014,
    INSUFFICIENT_MINERAL_DARK = 4015,
    MODULE_TYPE_MISMATCH = 4016,
    MODULE_TYPE_CHANGE_NOT_ALLOWED = 4017,
    INVALID_MODULE_TYPE = 4018,
    MODULE_ALREADY_RESEARCHED = 4019,
    FLEET_CONTROLLER_FAIL_INVALID_TOKEN = 103001,
    FLEET_CONTROLLER_FAIL_JWT_HAS_CHARACTERID = 103002,
    FLEET_CONTROLLER_FAIL_JWT_GET_CHARACTERID = 103003,
    UNLOCK_MODULE_FAIL_SHIP_NOT_FOUND = 110001,
    UNLOCK_MODULE_FAIL_FLEET_ACCESS_DENIED = 110002,
    UNLOCK_MODULE_FAIL_ALREADY_UNLOCKED = 110003,
    UNLOCK_MODULE_FAIL_CHARACTER_NOT_FOUND = 110004,
    UNLOCK_MODULE_FAIL_INSUFFICIENT_MINERAL = 110005,
    CLIENT_REFRESH_TOKEN_NULL = 500001,
    CLIENT_INVALID_TOKEN_NOT401_RETRY_COUNT_OVER = 500002,
    CLIENT_RUNASYNC_FAIL_UNKONW = 500003,
    CLIENT_AUTO_LOGIN_REFRESH_TOKEN_NOT_FOUND = 500004,
    CLIENT_AUTO_LOGIN_REFRESH_TOKEN_TRY_FAIL = 500005,
    CLIENT_DELETE_ACCOUNT_FAIL = 500006,
    INVALID_DATA_TABLE = 5001,
    UNKNOWN_ERROR = int.MaxValue,
}

public static class ErrorCodeMapping
{
    public static readonly Dictionary<ServerErrorCode, string> Messages = new Dictionary<ServerErrorCode, string>
    {
        { ServerErrorCode.SUCCESS, "Success" },
        { ServerErrorCode.HTTP_BAD_REQUEST_400, "HTTP_BAD_REQUEST_400" },
        { ServerErrorCode.HTTP_UNAUTHORIZED_401, "HTTP_UNAUTHORIZED_401" },
        { ServerErrorCode.HTTP_FORBIDDEN_403, "HTTP_FORBIDDEN_403" },
        { ServerErrorCode.HTTP_NOT_FOUND_404, "HTTP_NOT_FOUND_404" },
        { ServerErrorCode.HTTP_SERVER_ERROR_500, "HTTP_SERVER_ERROR_500" },
        { ServerErrorCode.ACCOUNT_REGISTER_FAIL_REASON1, "Account registration failed due to duplicate email" },
        { ServerErrorCode.LOGIN_FAIL_REASON1, "Invalid email or password" },
        { ServerErrorCode.ACCOUNT_NOT_FOUND, "Account not found" },
        { ServerErrorCode.LOGIN_GOOGLE_FAIL_AUTHENTICATION_TIMEOUT, "LOGIN_GOOGLE_FAIL_AUTHENTICATION_TIMEOUT" },
        { ServerErrorCode.LOGIN_GOOGLE_FAIL_EXTRACT_AUTHENTICATION, "LOGIN_GOOGLE_FAIL_EXTRACT_AUTHENTICATION" },
        { ServerErrorCode.INVALID_TOKEN, "Invalid token" },
        { ServerErrorCode.CHARACTER_CREATE_FAIL_REASON1, "Character creation failed" },
        { ServerErrorCode.CHARACTER_NAME_DUPLICATE, "Character name already exists" },
        { ServerErrorCode.CHARACTER_SELECTION_REQUIRED, "Character selection required" },
        { ServerErrorCode.CHARACTER_NOT_FOUND, "Character not found" },
        { ServerErrorCode.FLEET_NOT_FOUND, "Fleet not found" },
        { ServerErrorCode.FLEET_DUPLICATE_NAME, "Fleet name already exists" },
        { ServerErrorCode.FLEET_ACCESS_DENIED, "Fleet access denied" },
        { ServerErrorCode.SHIP_NOT_FOUND, "Ship not found" },
        { ServerErrorCode.MODULE_NOT_FOUND, "Module not found" },
        { ServerErrorCode.MODULE_LEVEL_MISMATCH, "Module level mismatch" },
        { ServerErrorCode.MODULE_DATA_NOT_FOUND, "Module data not found" },
        { ServerErrorCode.INSUFFICIENT_MONEY, "Insufficient money for upgrade" },
        { ServerErrorCode.INSUFFICIENT_MINERAL, "Insufficient mineral for upgrade" },
        { ServerErrorCode.ACTIVE_FLEET_NOT_FOUND, "Active fleet not found" },
        { ServerErrorCode.FLEET_MAX_SHIPS_REACHED, "Maximum ships per fleet reached" },
        { ServerErrorCode.INSUFFICIENT_TECH_LEVEL, "Insufficient tech level for upgrade" },
        { ServerErrorCode.INSUFFICIENT_MINERAL_RARE, "Insufficient rare mineral for upgrade" },
        { ServerErrorCode.INSUFFICIENT_MINERAL_EXOTIC, "Insufficient exotic mineral for upgrade" },
        { ServerErrorCode.INSUFFICIENT_MINERAL_DARK, "Insufficient dark mineral for upgrade" },
        { ServerErrorCode.MODULE_TYPE_MISMATCH, "Module type mismatch" },
        { ServerErrorCode.MODULE_TYPE_CHANGE_NOT_ALLOWED, "Module type change not allowed" },
        { ServerErrorCode.INVALID_MODULE_TYPE, "Invalid module type" },
        { ServerErrorCode.MODULE_ALREADY_RESEARCHED, "Module already researched" },
        { ServerErrorCode.FLEET_CONTROLLER_FAIL_INVALID_TOKEN, "FLEET_CONTROLLER_FAIL_INVALID_TOKEN" },
        { ServerErrorCode.FLEET_CONTROLLER_FAIL_JWT_HAS_CHARACTERID, "FLEET_CONTROLLER_FAIL_JWT_HAS_CHARACTERID" },
        { ServerErrorCode.FLEET_CONTROLLER_FAIL_JWT_GET_CHARACTERID, "FLEET_CONTROLLER_FAIL_JWT_GET_CHARACTERID" },
        { ServerErrorCode.UNLOCK_MODULE_FAIL_SHIP_NOT_FOUND, "UNLOCK_MODULE_FAIL_SHIP_NOT_FOUND" },
        { ServerErrorCode.UNLOCK_MODULE_FAIL_FLEET_ACCESS_DENIED, "UNLOCK_MODULE_FAIL_FLEET_ACCESS_DENIED" },
        { ServerErrorCode.UNLOCK_MODULE_FAIL_ALREADY_UNLOCKED, "UNLOCK_MODULE_FAIL_ALREADY_UNLOCKED" },
        { ServerErrorCode.UNLOCK_MODULE_FAIL_CHARACTER_NOT_FOUND, "UNLOCK_MODULE_FAIL_CHARACTER_NOT_FOUND" },
        { ServerErrorCode.UNLOCK_MODULE_FAIL_INSUFFICIENT_MINERAL, "UNLOCK_MODULE_FAIL_INSUFFICIENT_MINERAL" },
        { ServerErrorCode.CLIENT_REFRESH_TOKEN_NULL, "CLIENT_REFRESH_TOKEN_NULL" },
        { ServerErrorCode.CLIENT_INVALID_TOKEN_NOT401_RETRY_COUNT_OVER, "CLIENT_INVALID_TOKEN_NOT401_RETRY_COUNT_OVER" },
        { ServerErrorCode.CLIENT_RUNASYNC_FAIL_UNKONW, "CLIENT_RUNASYNC_FAIL_UNKONW" },
        { ServerErrorCode.CLIENT_AUTO_LOGIN_REFRESH_TOKEN_NOT_FOUND, "CLIENT_AUTO_LOGIN_REFRESH_TOKEN_NOT_FOUND" },
        { ServerErrorCode.CLIENT_AUTO_LOGIN_REFRESH_TOKEN_TRY_FAIL, "CLIENT_AUTO_LOGIN_REFRESH_TOKEN_TRY_FAIL" },
        { ServerErrorCode.CLIENT_DELETE_ACCOUNT_FAIL, "CLIENT_AUTO_LOGIN_REFRESH_TOKEN_TRY_FAIL" },
        { ServerErrorCode.INVALID_DATA_TABLE, "Invalid data table provided" },
        { ServerErrorCode.UNKNOWN_ERROR, "Unknown error" },
    };

    public static string GetMessage(int errorCode)
    {
        ServerErrorCode code = (ServerErrorCode)errorCode;
        return Messages.ContainsKey(code) ? Messages[code] : Messages[ServerErrorCode.UNKNOWN_ERROR];
    }
}